services:
  web:
    image: php:8.2-apache
    container_name: php-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    restart: always
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

  db:
    image: mysql:9.1.0
    container_name: science-institution-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=science-institution
    volumes:
      - ./data:/var/lib/mysql 
